import BowlingScores
#from json import loads
import json

def RunScoringTests():
    #read test cases
    print("--starting test run--")
    with open('TestCases.txt', 'r') as testcases:
        #split out details for each test case
        for tc in testcases:

            if tc.startswith("###"):
                print("--SUDDEN END!!--")
                break

            if tc.startswith("##"):
                print(f"\n{tc[2:]}")
                continue

            if not tc.strip() or tc.startswith("#"): 
                continue  #allow comments and blank lines but skip them

            tc = tc.strip()
            RunTestCase(tc)
    print("--ending test run--")


def RunTestCase(testcase):
    [tc_name, frames, expected_scores, expected_pass_fail] = testcase.strip().split("@")
    expected_pass_fail = True if expected_pass_fail.lower() == "true" else False
    print(f"\r\n\t--{tc_name}-- \r\n {frames=} \r\n {expected_scores=}  {expected_pass_fail=}")
    expected_scores = json.loads(expected_scores)

    try:
        each_frame_score, frames_added_up = BowlingScores.ScoreGame(frames)
        result = (frames_added_up == expected_scores) == expected_pass_fail
        print(f"Frame totals {each_frame_score}")
        print(f"Added up {frames_added_up}")
        print(f"Result={"PASS" if result else "FAIL"}")
    except ValueError as errror: # ValueError is generated by the code encountering badly formed games and other errors
        if not bool(expected_pass_fail):
            print(f"Expected ValueError exception  \r\nMessage={errror}")
            print("Result=PASS")
        else:
            print(f"Not expected ValueError --> {errror}")
            print("Result=FAIL")
    except Exception as e:  # no exception should stop the test run, but they should be noted
        print(f"Unexpected unknown exception --> {e}")
        print("Result=FAIL")


def main():
    print("--------------------")
    RunScoringTests()
    print("--------------------")

if __name__ == '__main__': main()
